"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthContainer from "@/shared/context/auth-context/auth-container";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "MERN STACK APP",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContainer>{children}</AuthContainer>
      </body>
    </html>
  );
}
